### ISSUE TITLE
Add node-fetch to dependencies

### ISSUE THREAD

**Issue by athulmurali** [austenstone/venmo-typescript#3]
```
node_modules/venmo-typescript/index.d.ts:1:26 - error TS2307: Cannot find module 'node-fetch' or its corresponding type declarations.

1 import { Response } from 'node-fetch';
                           ~~~~~~~~~~~~

```

Added  node-fetch to my project to fix this but looks like it is missing in the package.json here.

**Comment by demipixel** [comment]
Fixed in my fork ([PR here](https://github.com/austenstone/venmo-typescript/pull/5)) by switch to axios, if any future lurker is interested.
