### ISSUE TITLE
Fix incorrect values for "main" and "types" in package.json

### ISSUE THREAD

**Issue by borispetrovdev** [austenstone/venmo-typescript#7]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `venmo-typescript@2.0.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/venmo-typescript/package.json b/node_modules/venmo-typescript/package.json
index 557175c..c764075 100644
--- a/node_modules/venmo-typescript/package.json
+++ b/node_modules/venmo-typescript/package.json
@@ -2,8 +2,8 @@
   "name": "venmo-typescript",
   "version": "2.0.1",
   "description": "Class for interacting with the Venmo API.",
-  "main": "lib/markdown.js",
-  "types": "lib/markdown.d.ts",
+  "main": "./index.js",
+  "types": "./index.d.ts",
   "scripts": {
     "build": "tsc",
     "test": "jest",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by austenstone** [comment]
We should be good now
https://github.com/austenstone/venmo-typescript/blob/bec48711329f431575241d8ae5a12afd59136d81/package.json#L5-L6
